language: python
arch:
  - amd64
  - ppc64le
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install: "pip install pytest coveralls --use-mirrors"
script: "coverage run $(which py.test)"
after_success: "coveralls"
